name: Monthly Slack Reminders

on:
  schedule:
    - cron: '0 4 1-7 * 1'     # 첫째 주 월요일 오후 1시 (KST)
    - cron: '0 4 15-21 * 1'   # 셋째 주 월요일 오후 1시 (KST)

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send reminder to Slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          IMAGE_URL="https://github.com/kasurashan/img-test/blob/main/ai-trend-1.png?raw=true"
          NOW=$(date +%d)
          if [ $NOW -ge 15 ]; then
            IMAGE_URL="https://github.com/kasurashan/img-test/blob/main/ai-trend-2.png?raw=true"
          fi

          curl -X POST -H "Authorization: Bearer $SLACK_TOKEN" \
            -H 'Content-type: application/json' \
            --data "{
              \"channel\": \"#general\",
              \"text\": \"Let’s try to have everyone in this channel post at least once a month!\",
              \"attachments\": [
                {
                  \"fallback\": \"슬랙 리마인더 이미지\",
                  \"image_url\": \"${IMAGE_URL}\",
                  \"text\": \"AI is changing fast, and it’s hard to keep up alone. If we all share more, we can spot trends faster and find areas we’re good at together.\"
                }
              ]
            }" \
            https://slack.com/api/chat.postMessage
