name: Monthly Slack Reminders

# 매주 월요일 13:00 KST → UTC 04:00
on:
  schedule:
    - cron: '0 4 * * 1'
  # workflow_dispatch:  # 수동 실행 허용하려면 주석 해제

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: 첫째·셋째 주 월요일인지 체크  
        id: week-check
        run: |
          # Asia/Seoul 기준 날짜 가져오기
          DAY=$(TZ=Asia/Seoul date +'%d')
          if [ "$DAY" -le 7 ] || { [ "$DAY" -ge 15 ] && [ "$DAY" -le 21 ]; }; then
            echo "should_post=true" >> $GITHUB_OUTPUT
          else
            echo "should_post=false" >> $GITHUB_OUTPUT
          fi

      - name: Send reminder to Slack
        if: steps.week-check.outputs.should_post == 'true'
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          TZ: Asia/Seoul
        run: |
          # ❷ 15일 이후면 다른 이미지
          IMAGE_URL="https://github.com/kasurashan/slack-reminder/blob/main/ai-trend-1.png?raw=true"
          TODAY=$(date +'%d')
          if [ "$TODAY" -ge 15 ]; then
            IMAGE_URL="https://github.com/kasurashan/slack-reminder/blob/main/ai-trend-2.png?raw=true"
          fi

          # ❸ payload 생성 및 전송
          jq -n --arg url "$IMAGE_URL" '
          {
            channel:"#ai-trend",
            text:"Let’s try to have everyone in this channel post at least once a month!",
            attachments:[
              {
                fallback:"슬랙 리마인더 이미지",
                image_url:$url,
                text:"AI is changing fast, and it’s hard to keep up alone. If we all share more, we can spot trends faster and find areas we’re good at together."
              }
            ]
          }' > payload.json

          curl -s -X POST \
            -H "Authorization: Bearer $SLACK_TOKEN" \
            -H "Content-Type: application/json; charset=utf-8" \
            --data @payload.json \
            https://slack.com/api/chat.postMessage | jq .
